### ISSUE TITLE
Sadly www.foundweekends.org is not live

### ISSUE THREAD

**Issue by langley** [foundweekends/foundweekends.github.io#1]
I see the CNAME, but it seems it's not registered :-/ 

I have to say that I am one of those people who codes more scala on the weekend than I do at work these days, not that I never do; but I'm stuck working in other languages more than I'd like.

**Comment by eed3si9n** [comment]
http://www.foundweekends.org/ works for me.

**Comment by langley** [comment]
Works now. This was an ancient issue that has apparently been resolved.

**Comment by langley** [comment]
Works now. This was an ancient issue that has apparently been resolved.
