### ISSUE TITLE
"The custom domain for your GitHub Pages site is pointed at an outdated IP address."

### ISSUE THREAD

**Issue by xuwei-k** [foundweekends/foundweekends.github.io#4]
> 
> The page build completed successfully, but returned the following warning for the `master` branch:
> 
> The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://docs.github.com/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://docs.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can submit a request on the Contact GitHub page at https://support.github.com/contact?repo_id=54762356&page_build_id=217255430
>

**Comment by eed3si9n** [comment]
According to https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#about-custom-domain-configuration these both need to be updated:

```
$ dig www.foundweekends.org +nostats +nocomments +nocmd

; <<>> DiG 9.10.6 <<>> www.foundweekends.org +nostats +nocomments +nocmd
;; global options: +cmd
;www.foundweekends.org.		IN	A
www.foundweekends.org.	725	IN	A	192.30.252.153

$ dig foundweekends.org +noall +answer

; <<>> DiG 9.10.6 <<>> foundweekends.org +noall +answer
;; global options: +cmd
foundweekends.org.	899	IN	A	192.30.252.153
```

**Comment by eed3si9n** [comment]
They were updated as follows:

```
$ dig www.foundweekends.org +nostats +nocomments +nocmd

; <<>> DiG 9.10.6 <<>> www.foundweekends.org +nostats +nocomments +nocmd
;; global options: +cmd
;www.foundweekends.org.		IN	A
www.foundweekends.org.	899	IN	CNAME	foundweekends.github.io.
foundweekends.github.io. 3599	IN	A	185.199.109.153
foundweekends.github.io. 3599	IN	A	185.199.110.153
foundweekends.github.io. 3599	IN	A	185.199.111.153
foundweekends.github.io. 3599	IN	A	185.199.108.153

$ dig foundweekends.org +noall +answer

; <<>> DiG 9.10.6 <<>> foundweekends.org +noall +answer
;; global options: +cmd
foundweekends.org.	899	IN	A	185.199.111.153
foundweekends.org.	899	IN	A	185.199.108.153
foundweekends.org.	899	IN	A	185.199.109.153
foundweekends.org.	899	IN	A	185.199.110.153
```
